import 'package:flutter/material.dart';
import '../../services/app_session.dart';
import '../../widgets/app_shell.dart';
import 'mobile_widgets.dart';

class DeviceEditorScreen extends StatefulWidget{final AppSession session;final Map<String,dynamic> device;const DeviceEditorScreen({super.key,required this.session,required this.device});@override State<DeviceEditorScreen> createState()=>_DeviceEditorScreenState();}
class _DeviceEditorScreenState extends State<DeviceEditorScreen>{late final TextEditingController name,code;int? locationId;@override void initState(){super.initState();name=TextEditingController(text:widget.device['name']?.toString()??'');code=TextEditingController(text:widget.device['code']?.toString()??'');locationId=int.tryParse('${widget.device['location_id']}');}@override void dispose(){name.dispose();code.dispose();super.dispose();}
Future<void> save()async{if(name.text.trim().isEmpty){showSessionMessage(context,'Cihaz adını girin.');return;}final ok=await widget.session.updateDevice(int.parse('${widget.device['id']}'),name:name.text.trim(),code:code.text.trim(),locationId:locationId);if(!mounted)return;if(ok)Navigator.pop(context);else showSessionMessage(context,widget.session.error??'Cihaz güncellenemedi.');}
@override Widget build(BuildContext context){final targets=widget.session.locations.where((l)=>l['type']=='room'||l['type']=='cabinet').toList();return Scaffold(body:AppBackground(child:ListView(padding:const EdgeInsets.fromLTRB(18,6,18,30),children:[MobileTopBar(title:'Cihazı Düzenle',subtitle:widget.device['code']?.toString(),actions:[IconButton(onPressed:()=>Navigator.pop(context),icon:const Icon(Icons.close))]),Panel(child:Column(children:[TextField(controller:name,decoration:const InputDecoration(labelText:'Cihaz adı',prefixIcon:Icon(Icons.memory))),const SizedBox(height:12),TextField(controller:code,readOnly:true,decoration:const InputDecoration(labelText:'Seri numarası / cihaz kodu',prefixIcon:Icon(Icons.qr_code_2),helperText:'Güvenlik için mevcut cihaz kodu bu ekranda değiştirilmez.')),const SizedBox(height:12),DropdownButtonFormField<int>(value:locationId,decoration:const InputDecoration(labelText:'Oda / dolap',prefixIcon:Icon(Icons.meeting_room_outlined)),items:[const DropdownMenuItem<int>(value:null,child:Text('Atanmamış')),...targets.map((l)=>DropdownMenuItem<int>(value:int.tryParse('${l['id']}'),child:Text(locationPath(widget.session.locations,l['id'])))).where((x)=>x.value!=null)],onChanged:(v)=>setState(()=>locationId=v)),const SizedBox(height:18),PrimaryButton(text:widget.session.busy?'KAYDEDİLİYOR...':'DEĞİŞİKLİKLERİ KAYDET',icon:Icons.save_outlined,onPressed:widget.session.busy?null:save)]))])));}}
