import 'package:flutter/material.dart';
import '../../services/app_session.dart';
import '../../theme/app_theme.dart';
import '../../widgets/app_shell.dart';
import 'mobile_widgets.dart';

class SensorEditorScreen extends StatefulWidget{final AppSession session;final Map<String,dynamic> device;final Map<String,dynamic>? sensor;const SensorEditorScreen({super.key,required this.session,required this.device,this.sensor});@override State<SensorEditorScreen> createState()=>_SensorEditorScreenState();}
class _SensorEditorScreenState extends State<SensorEditorScreen>{String? metric;bool enabled=true;late final TextEditingController minC,maxC;int alarmValue=1;
@override void initState(){super.initState();final s=widget.sensor;metric=s?['metric']?.toString();enabled=s==null?true:truthy(s['enabled']);minC=TextEditingController(text:s?['min_value']?.toString()??'');maxC=TextEditingController(text:s?['max_value']?.toString()??'');alarmValue=int.tryParse('${s?['alarm_value']??1}')??1;}
@override void dispose(){minC.dispose();maxC.dispose();super.dispose();}
List<String> metrics(){final c=widget.session.metricCatalog;final out=c.entries.where((e)=>e.value is Map&&Map<String,dynamic>.from(e.value as Map)['selectable']!=false).map((e)=>e.key).toList();out.sort((a,b)=>metricLabel(a,c).compareTo(metricLabel(b,c)));return out;}
Future<void> save()async{if(metric==null){showSessionMessage(context,'Sensör türünü seçin.');return;}final digital=metric=='smoke'||metric=='fire';final min=double.tryParse(minC.text.trim().replaceAll(',','.'));final max=double.tryParse(maxC.text.trim().replaceAll(',','.'));if(!digital&&min!=null&&max!=null&&min>=max){showSessionMessage(context,'Alt eşik üst eşikten küçük olmalı.');return;}final ok=await widget.session.saveSensor(id:widget.sensor==null?null:int.parse('${widget.sensor!['id']}'),deviceId:int.parse('${widget.device['id']}'),metric:metric!,enabled:enabled,minValue:digital?null:min,maxValue:digital?null:max,alarmValue:alarmValue);if(!mounted)return;if(ok)Navigator.pop(context);else showSessionMessage(context,widget.session.error??'Sensör kaydedilemedi.');}
@override Widget build(BuildContext context){final c=widget.session.metricCatalog;final available=metrics();final digital=metric=='smoke'||metric=='fire';return Scaffold(body:AppBackground(child:ListView(padding:const EdgeInsets.fromLTRB(18,6,18,30),children:[MobileTopBar(title:widget.sensor==null?'Sensör Ekle':'Sensörü Düzenle',subtitle:widget.device['name']?.toString(),actions:[IconButton(onPressed:()=>Navigator.pop(context),icon:const Icon(Icons.close))]),Panel(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[DropdownButtonFormField<String>(value:metric,decoration:const InputDecoration(labelText:'Sensör türü',prefixIcon:Icon(Icons.sensors)),items:available.map((m)=>DropdownMenuItem(value:m,child:Text('${metricLabel(m,c)}${metricUnit(m,c).isEmpty?'':' · ${metricUnit(m,c)}'}'))).toList(),onChanged:widget.sensor==null?(v)=>setState(()=>metric=v):null),const SizedBox(height:12),SwitchListTile(contentPadding:EdgeInsets.zero,title:const Text('İzlemeye al',style:TextStyle(fontWeight:FontWeight.w800)),subtitle:const Text('Sensör aktif izlemeye dahil edilir.',style:TextStyle(color:AppTheme.muted,fontSize:11)),value:enabled,onChanged:(v)=>setState(()=>enabled=v)),if(metric!=null)...[const SizedBox(height:8),if(digital)DropdownButtonFormField<int>(value:alarmValue,decoration:const InputDecoration(labelText:'Alarm değeri'),items:const [DropdownMenuItem(value:1,child:Text('1 = Alarm')),DropdownMenuItem(value:0,child:Text('0 = Alarm'))],onChanged:(v)=>setState(()=>alarmValue=v??1))else Row(children:[Expanded(child:TextField(controller:minC,keyboardType:const TextInputType.numberWithOptions(decimal:true,signed:true),decoration:const InputDecoration(labelText:'Alt eşik'))),const SizedBox(width:10),Expanded(child:TextField(controller:maxC,keyboardType:const TextInputType.numberWithOptions(decimal:true,signed:true),decoration:const InputDecoration(labelText:'Üst eşik')))])],const SizedBox(height:18),PrimaryButton(text:widget.session.busy?'KAYDEDİLİYOR...':'SENSÖRÜ KAYDET',icon:Icons.save_outlined,onPressed:widget.session.busy?null:save)]))])));}}
